#!/usr/bin/env node
/**
 * gen-data.mjs — 从 GrokBot (https://github.com/nasawz/GrokBot) 的 Dart 数据源
 * 解析出 Web 端使用的数据，生成 src/client/data.js（纯脚本、无 ESM）。
 *
 * 解析对象：
 *   - expression_data.dart  → 25 个表情 × 2 只眼 × 48 个点（TB_EXPRESSIONS）
 *   - shape_data.dart       → 18 种形态参数（TB_SHAPES，radius 即 CSS border-radius 语法）
 *   - state_data.dart       → 39 种状态的表情池与节奏（TB_STATES）
 *
 * 用法：node scripts/gen-data.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dataDir = join(root, 'ref', 'GrokBot', 'lib', 'src', 'data')
const outFile = join(root, 'src', 'client', 'data.js')

const read = (name) => readFileSync(join(dataDir, name), 'utf8')

/** 全部 Offset(x, y) 按顺序取出，每 96 个点（2 眼 × 48）为一个表情。 */
function parseExpressions(source) {
  const points = []
  const re = /Offset\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/g
  let m
  while ((m = re.exec(source)) !== null) {
    points.push([Number(m[1]), Number(m[2])])
  }
  const PER_EXPRESSION = 96 // 2 eyes × 48 points
  if (points.length % PER_EXPRESSION !== 0) {
    throw new Error(`expression points not divisible: ${points.length}`)
  }
  const expressions = []
  for (let i = 0; i < points.length; i += PER_EXPRESSION) {
    const chunk = points.slice(i, i + PER_EXPRESSION)
    const eyeL = chunk.slice(0, 48)
    const eyeR = chunk.slice(48, 96)
    expressions.push([eyeL, eyeR])
  }
  return expressions
}

/** 每个 GrokBotShape.X: GrokBotShapeData(...) 条目解析出 9 个字段。 */
function parseShapes(source) {
  const shapes = {}
  const entryRe = /GrokBotShape\.(\w+):\s*GrokBotShapeData\(([\s\S]*?)\),\s*$/gm
  const fieldRe = /([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*(true|false)\s*,\s*'([^']*)'\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)/g
  let m
  while ((m = entryRe.exec(source)) !== null) {
    const name = m[1]
    const fields = m[2]
    fieldRe.lastIndex = 0
    const f = fieldRe.exec(fields)
    if (!f) throw new Error(`shape fields not parsed: ${name}`)
    shapes[name] = {
      faceX: Number(f[1]),
      faceY: Number(f[2]),
      faceScaleX: Number(f[3]),
      faceScaleY: Number(f[4]),
      eyeScale: Number(f[5]),
      squashOnTurn: f[6] === 'true',
      radius: f[7],
      aspectX: Number(f[8]),
      aspectY: Number(f[9]),
    }
  }
  return shapes
}

/** 每个 GrokBotState.X: GrokBotStateData(...) 条目解析出表情池与两个节奏。 */
function parseStates(source) {
  const states = {}
  const entryRe =
    /GrokBotState\.(\w+):\s*GrokBotStateData\(\s*_expressions\(\[([\d,\s]+)\]\),\s*_cadence\((\d+),\s*(\d+)\),\s*(?:_cadence\((\d+),\s*(\d+)\))?/g
  let m
  while ((m = entryRe.exec(source)) !== null) {
    const name = m[1]
    const indexes = m[2].split(',').map((s) => Number(s.trim()))
    states[name] = {
      expressions: indexes,
      expressionMin: Number(m[3]),
      expressionMax: Number(m[4]),
      blinkMin: m[5] !== undefined ? Number(m[5]) : null,
      blinkMax: m[6] !== undefined ? Number(m[6]) : null,
    }
  }
  return states
}

const expressions = parseExpressions(read('expression_data.dart'))
const shapes = parseShapes(read('shape_data.dart'))
const states = parseStates(read('state_data.dart'))

if (expressions.length !== 25) throw new Error(`expected 25 expressions, got ${expressions.length}`)
if (Object.keys(shapes).length !== 18) throw new Error(`expected 18 shapes, got ${Object.keys(shapes).length}`)
if (Object.keys(states).length !== 39) throw new Error(`expected 39 states, got ${Object.keys(states).length}`)

const header = `/* Generated by scripts/gen-data.mjs from nasawz/GrokBot (BSD-3-Clause, (c) 2026 nasawz,
   https://github.com/nasawz/GrokBot). Ported geometry: 25 expressions × 2 eyes × 48
   points, 18 body shapes (CSS border-radius syntax), 39 states with expression/blink
   cadences. Do not edit by hand — re-run the generator after upstream changes. */`

const body = [
  header,
  `const TB_EXPRESSIONS = ${JSON.stringify(expressions)};`,
  `const TB_SHAPES = ${JSON.stringify(shapes)};`,
  `const TB_STATES = ${JSON.stringify(states)};`,
  '',
].join('\n')

writeFileSync(outFile, body)
console.log(`ok: ${outFile}`)
console.log(`  expressions=${expressions.length} (${expressions.length * 96} points)`)
console.log(`  shapes=${Object.keys(shapes).length}`)
console.log(`  states=${Object.keys(states).length}`)
console.log(`  bytes=${Buffer.byteLength(body)}`)
